name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (used for name of the release)"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: |
          dotnet publish --runtime win-x64 -p:Configuration=Release -p:PublishSingleFile=true
          dotnet publish --runtime osx-x64 -p:Configuration=Release -p:PublishSingleFile=true
          dotnet publish --runtime linux-x64 -p:Configuration=Release -p:PublishSingleFile=true

      - name: Rename
        run: |
          ren ./bin/Release/net8.0/win-x64/publish/CsvTools.exe CsvTools_win-x64.exe
          ren ./bin/Release/net8.0/osx-x64/publish/CsvTools CsvTools_osx-x64
          ren ./bin/Release/net8.0/linux-x64/publish/CsvTools CsvTools_linux-x64

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: v${{inputs.version}}
          tag: ${{inputs.version}}
          artifacts: "./bin/Release/net8.0/win-x64/publish/CsvTools_win-x64.exe, ./bin/Release/net8.0/osx-x64/publish/CsvTools_osx-x64, ./bin/Release/net8.0/linux-x64/publish/CsvTools_linux-x64"
